ktor {
  environment = development
  environment = ${?KTOR_ENV}

  application {
    modules = [ua.vald_zx.game.rat.race.server.ApplicationKt.module]
  }

  deployment {
    host = 0.0.0.0
    host = ${?HOST}
    port = 8080
    port = ${?PORT}
  }

  logger {
    level = INFO
    level = ${?KTOR_LOGGER_LEVEL_INFO}
  }
}
