package ua.vald_zx.game.rat.race.server.generation

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.sync.Semaphore
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.json.put
import ua.vald_zx.game.rat.race.card.shared.GenerationQuotaType
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration
import java.util.concurrent.atomic.AtomicReference

private val llmQuotaTracker = LlmQuotaTracker()
private val llmHttpClient: HttpClient by lazy {
    HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(20)).build()
}

internal data class LlmTokenUsage(
    val input: Long,
    val output: Long,
    val total: Long,
    val quota: LlmQuotaSnapshot? = null,
)

internal data class LlmRetryWait(
    val provider: String,
    val model: String,
    val delayMillis: Long,
    val quota: LlmQuotaSnapshot? = null,
)

internal fun interface ChatCompletion {
    suspend fun complete(system: String, user: String): String?
}

internal class LlmProviderPool(
    private val members: List<Member>,
    private val maxWaitMillis: Long = MAX_POOL_WAIT_MILLIS,
    private val onRetry: suspend (LlmRetryWait) -> Unit = {},
    private val nowEpochMs: () -> Long = System::currentTimeMillis,
    private val wait: suspend (Long) -> Unit = { delay(it) },
) : ChatCompletion {

    internal class Member(
        val provider: String,
        val model: String,
        val completion: ChatCompletion,
        val fallbackOnly: Boolean = false,
    ) {
        internal val slot = Semaphore(1)
        internal val cooldown = AtomicReference<Cooldown?>(null)

        val name: String get() = "$provider/$model"

        fun availableAt(now: Long): Long = cooldown.get()
            ?.takeIf { it.untilEpochMs > now }
            ?.untilEpochMs
            ?: now
    }

    override suspend fun complete(system: String, user: String): String? {
        val exhausted = mutableSetOf<Member>()
        var waitedMillis = 0L
        var lastFailure: LlmProviderException? = null
        while (true) {
            val candidates = members.filterNot { it in exhausted }
            if (candidates.isEmpty()) break
            val now = nowEpochMs()
            val ready = candidates.filter { it.availableAt(now) <= now }
            if (ready.isEmpty()) {
                val soonest = candidates.minBy { it.availableAt(now) }
                val delayMillis = (soonest.availableAt(now) - now).coerceAtLeast(0)
                if (waitedMillis + delayMillis > maxWaitMillis) break
                waitedMillis += delayMillis
                llmLogger.warn("Every LLM provider is cooling down, waiting ${delayMillis}ms for ${soonest.name}")
                onRetry(LlmRetryWait(soonest.provider, soonest.model, delayMillis, soonest.cooldown.get()?.quota))
                wait(delayMillis)
                continue
            }
            val regular = ready.filterNot { it.fallbackOnly }
            val eligible = regular.ifEmpty { ready }
            val member = eligible.firstOrNull { it.slot.tryAcquire() }
                ?: eligible.first().also { it.slot.acquire() }
            var coolingDown = false
            val answer = try {
                member.completion.complete(system, user)
            } catch (rateLimit: LlmRateLimitException) {
                coolingDown = true
                member.cooldown.set(Cooldown(nowEpochMs() + rateLimit.retryAfterMillis, rateLimit.quota))
                lastFailure = rateLimit
                llmLogger.warn(
                    "${member.name} is rate limited, cooling it down for ${rateLimit.retryAfterMillis}ms"
                )
                null
            } catch (failure: LlmProviderException) {
                lastFailure = failure
                llmLogger.warn("${failure.message}; excluding ${member.name} from this request")
                null
            } finally {
                member.slot.release()
            }
            if (answer != null) {
                llmLogger.info("LLM response generated by ${member.name}")
                return answer
            }
            if (!coolingDown) exhausted += member
        }
        lastFailure?.let { throw it }
        return null
    }
}

internal data class Cooldown(
    val untilEpochMs: Long,
    val quota: LlmQuotaSnapshot?,
)

internal class HttpChatCompletion(
    private val provider: LlmProviderSettings,
    private val model: String,
    private val extraBody: JsonObject? = null,
    private val maxOutputTokens: Int = MAX_BALANCE_COMPLETION_TOKENS,
    private val onUsage: suspend (LlmTokenUsage) -> Unit = {},
    private val onQuota: suspend (LlmQuotaSnapshot) -> Unit = {},
    private val wait: suspend (Long) -> Unit = { delay(it) },
    private val quotaTracker: LlmQuotaTracker = llmQuotaTracker,
    private val nowEpochMs: () -> Long = System::currentTimeMillis,
    private val client: HttpClient = llmHttpClient,
) : ChatCompletion {

    private val json = Json { ignoreUnknownKeys = true }

    @Volatile
    private var extrasRejected = false

    override suspend fun complete(system: String, user: String): String? = withContext(Dispatchers.IO) {
        var withExtras = extraBody != null && !extrasRejected
        var failedAttempts = 0
        while (true) {
            val payload = payload(system, user, withExtras)
            val request = HttpRequest.newBuilder(URI.create(provider.url))
                .timeout(Duration.ofSeconds(120))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer ${provider.key}")
                .POST(HttpRequest.BodyPublishers.ofString(payload.toString(), Charsets.UTF_8))
                .build()
            val response = runCatching {
                client.send(request, HttpResponse.BodyHandlers.ofString(Charsets.UTF_8))
            }.onFailure {
                llmLogger.warn("LLM call failed: ${it.message}")
            }.getOrNull()
            if (response == null) {
                failedAttempts += 1
                if (failedAttempts >= MAX_LLM_REQUEST_ATTEMPTS) return@withContext null
                continue
            }
            if (response.statusCode() == 429) {
                val reportedRetry = response.retryDelay()
                val quota = response.reportedQuota()?.let { reported ->
                    quotaTracker.recordLimit(
                        provider = provider.name,
                        model = model,
                        type = reported.type,
                        limit = reported.limit,
                        retryDelayMillis = reportedRetry,
                    )
                }
                quota?.let { onQuota(it) }
                val retryAfterMillis = quota?.takeIf { it.type.isDailyQuota }
                    ?.let { maxOf(reportedRetry, it.resetAtEpochMs - nowEpochMs()) }
                    ?: reportedRetry
                throw LlmRateLimitException(provider.name, model, retryAfterMillis, quota)
            }
            if (response.statusCode() in 500..599) {
                val message = response.errorMessage()
                failedAttempts += 1
                if (failedAttempts < MAX_LLM_UNAVAILABLE_ATTEMPTS) {
                    val waitMillis = UNAVAILABLE_RETRY_DELAY_MILLIS * failedAttempts
                    llmLogger.warn(
                        "${provider.name}/$model temporarily unavailable: $message; retrying in ${waitMillis}ms"
                    )
                    wait(waitMillis)
                    continue
                }
                throw LlmProviderException("${provider.name}/$model is unavailable: $message")
            }
            if (response.statusCode() !in 200..299) {
                if (withExtras) {
                    extrasRejected = true
                    withExtras = false
                    llmLogger.warn(
                        "${provider.name}/$model rejected the extra request fields " +
                                "(${response.statusCode()}: ${response.errorMessage()}), retrying without them"
                    )
                    continue
                }
                throw LlmProviderException(
                    "${provider.name}/$model answered ${response.statusCode()}: ${response.errorMessage()}"
                )
            }
            val responseObject = json.parseToJsonElement(response.body()).jsonObject
            responseObject.tokenUsageOrNull()?.let { usage ->
                val quota = quotaTracker.recordSuccess(provider.name, model, usage.input)
                onUsage(usage.copy(quota = quota))
            }
            val choice = responseObject["choices"]?.jsonArray?.firstOrNull()?.jsonObject
                ?: throw LlmProviderException("${provider.name}/$model returned no choices")
            return@withContext choice["message"]?.jsonObject?.get("content")
                ?.jsonPrimitive?.contentOrNull
                ?: throw LlmProviderException(
                    "${provider.name}/$model returned no text (${choice["finish_reason"]?.jsonPrimitive?.contentOrNull ?: "unknown reason"})"
                )
        }
        @Suppress("UNREACHABLE_CODE")
        return@withContext null
    }

    private fun payload(system: String, user: String, withExtras: Boolean) = buildJsonObject {
        put("model", model)
        put("max_tokens", maxOutputTokens)
        put("messages", buildJsonArray {
            add(message("system", system))
            add(message("user", user))
        })
        if (withExtras) extraBody?.forEach { (field, value) -> put(field, value) }
    }

    private fun message(role: String, content: String) = buildJsonObject {
        put("role", role)
        put("content", content)
    }

    private fun HttpResponse<String>.retryDelay(): Long {
        val headerSeconds = headers().firstValue("Retry-After").orElse(null)?.toDoubleOrNull()
        val responseBody = body()
        val bodyDelay = RETRY_INFO_DELAY_PATTERN.find(responseBody)?.groupValues?.get(1)?.retryDurationMillis()
            ?: RETRY_MESSAGE_DELAY_PATTERN.find(responseBody)?.groupValues?.get(1)?.retryDurationMillis()
        val value = headerSeconds?.times(1_000)?.toLong() ?: bodyDelay ?: DEFAULT_RETRY_DELAY_MILLIS
        return value.coerceIn(MIN_RETRY_DELAY_MILLIS, MAX_REPORTED_RETRY_DELAY_MILLIS) + RETRY_DELAY_BUFFER_MILLIS
    }

    private fun HttpResponse<String>.errorMessage(): String =
        ERROR_MESSAGE_PATTERN.find(body())?.groupValues?.get(1)
            ?: body().take(MAX_ERROR_MESSAGE_LENGTH).ifBlank { "empty response" }

    private fun HttpResponse<String>.reportedQuota(): ReportedQuota? {
        val responseObject = runCatching { json.parseToJsonElement(body()).jsonObject }.getOrNull() ?: return null
        val details = runCatching {
            responseObject["error"]?.jsonObject?.get("details")?.jsonArray
        }.getOrNull() ?: return null
        return details.flatMap { detail ->
            runCatching { detail.jsonObject["violations"]?.jsonArray.orEmpty() }.getOrDefault(emptyList())
        }.mapNotNull { violation ->
            val value = runCatching { violation.jsonObject }.getOrNull() ?: return@mapNotNull null
            val quotaId = value["quotaId"]?.jsonPrimitive?.contentOrNull.orEmpty()
            val metric = value["quotaMetric"]?.jsonPrimitive?.contentOrNull.orEmpty()
            val limit = value["quotaValue"]?.jsonPrimitive?.longOrNull ?: return@mapNotNull null
            ReportedQuota(quotaType("$quotaId $metric"), limit)
        }.maxByOrNull { it.type.priority }
    }

    private fun JsonObject.tokenUsageOrNull(): LlmTokenUsage? {
        val usage = runCatching { get("usage")?.jsonObject }.getOrNull() ?: return null
        val input = usage["prompt_tokens"]?.jsonPrimitive?.longOrNull ?: 0
        val output = usage["completion_tokens"]?.jsonPrimitive?.longOrNull ?: 0
        val total = usage["total_tokens"]?.jsonPrimitive?.longOrNull ?: (input + output)
        return LlmTokenUsage(input, output, total).takeIf { it.total > 0 }
    }
}

private data class ReportedQuota(
    val type: GenerationQuotaType,
    val limit: Long,
)

internal open class LlmProviderException(message: String) : IllegalStateException(message)

internal class LlmRateLimitException(
    provider: String,
    model: String,
    val retryAfterMillis: Long,
    val quota: LlmQuotaSnapshot? = null,
) : LlmProviderException(
    "LLM rate limit reached for $provider/$model. Try again in ${retryAfterMillis.retryDelayText()}",
)

private fun quotaType(value: String): GenerationQuotaType {
    val normalized = value.lowercase().filter(Char::isLetterOrDigit)
    return when {
        "inputtoken" in normalized && "perday" in normalized -> GenerationQuotaType.INPUT_TOKENS_PER_DAY
        "request" in normalized && "perday" in normalized -> GenerationQuotaType.REQUESTS_PER_DAY
        "inputtoken" in normalized && "perminute" in normalized -> GenerationQuotaType.INPUT_TOKENS_PER_MINUTE
        "request" in normalized && "perminute" in normalized -> GenerationQuotaType.REQUESTS_PER_MINUTE
        "spend" in normalized -> GenerationQuotaType.SPEND_PER_TEN_MINUTES
        else -> GenerationQuotaType.UNKNOWN
    }
}

private val GenerationQuotaType.priority: Int
    get() = when (this) {
        GenerationQuotaType.REQUESTS_PER_DAY,
        GenerationQuotaType.INPUT_TOKENS_PER_DAY -> 3
        GenerationQuotaType.SPEND_PER_TEN_MINUTES -> 2
        GenerationQuotaType.REQUESTS_PER_MINUTE,
        GenerationQuotaType.INPUT_TOKENS_PER_MINUTE -> 1
        GenerationQuotaType.UNKNOWN -> 0
    }

private val GenerationQuotaType.isDailyQuota: Boolean
    get() = this == GenerationQuotaType.REQUESTS_PER_DAY || this == GenerationQuotaType.INPUT_TOKENS_PER_DAY

private fun String.retryDurationMillis(): Long = RETRY_DURATION_PART_PATTERN.findAll(this).sumOf { match ->
    val amount = match.groupValues[1].toDoubleOrNull() ?: return@sumOf 0L
    when (match.groupValues[2].lowercase()) {
        "h" -> amount.times(60 * 60 * 1_000).toLong()
        "m" -> amount.times(60 * 1_000).toLong()
        "s" -> amount.times(1_000).toLong()
        else -> amount.toLong()
    }
}

private fun Long.retryDelayText(): String = when {
    this >= 60 * 60 * 1_000 -> "${(this + 60 * 60 * 1_000 - 1) / (60 * 60 * 1_000)} h"
    this >= 60 * 1_000 -> "${(this + 60 * 1_000 - 1) / (60 * 1_000)} min"
    else -> "${(this + 1_000 - 1) / 1_000} s"
}

private const val MAX_LLM_REQUEST_ATTEMPTS = 8
private const val MAX_LLM_UNAVAILABLE_ATTEMPTS = 3
private const val MAX_BALANCE_COMPLETION_TOKENS = 8_000
private const val UNAVAILABLE_RETRY_DELAY_MILLIS = 2_000L
private const val MAX_ERROR_MESSAGE_LENGTH = 300
private const val MAX_POOL_WAIT_MILLIS = 5 * 60 * 1_000L
private const val DEFAULT_RETRY_DELAY_MILLIS = 3_000L
private const val MIN_RETRY_DELAY_MILLIS = 500L
private const val MAX_REPORTED_RETRY_DELAY_MILLIS = 24 * 60 * 60 * 1_000L
private const val RETRY_DELAY_BUFFER_MILLIS = 300L
private val RETRY_INFO_DELAY_PATTERN = Regex(
    "\\\"retryDelay\\\"\\s*:\\s*\\\"((?:[\\d.]+(?:ms|[hms]))+)\\\"",
    RegexOption.IGNORE_CASE,
)
private val RETRY_MESSAGE_DELAY_PATTERN = Regex(
    "(?:please\\s+)?(?:try\\s+again|retry)\\s+in\\s+((?:[\\d.]+(?:ms|[hms]))+)",
    RegexOption.IGNORE_CASE,
)
private val ERROR_MESSAGE_PATTERN = Regex("\\\"message\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"")
private val RETRY_DURATION_PART_PATTERN = Regex("([\\d.]+)(ms|[hms])", RegexOption.IGNORE_CASE)
