package ua.vald_zx.game.rat.race.card.screen.board.cards

import ua.vald_zx.game.rat.race.card.screen.board.BoardCard
import ua.vald_zx.game.rat.race.card.screen.board.PayerType

val expensesCards = mapOf(
    1 to BoardCard.Expenses(
        description = "Не втримався/лась і купив/ла великий флакон парфумів «Max Mara».",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    2 to BoardCard.Expenses(
        description = "Гадаю, ти весь час програєш у теніс тому, що в тебе стара ракетка… Купи нову ракетку з полегшеною ручкою!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    3 to BoardCard.Expenses(
        description = "У тебе болять зуби!!! Терміново відвідай стоматолога! Ти ж знаєш, далі буде тільки гірше! Зуби самі не одужують!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    4 to BoardCard.Expenses(
        description = "Ти купив/ла собі новий потужний пилосос!",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.ALL,
    ),
    5 to BoardCard.Expenses(
        description = "На трасі каменем розбило лобове скло — купи нове.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.AUTO_OWNER,
    ),
    6 to BoardCard.Expenses(
        description = "Твій підліток-син телефонував у «секс по телефону» — оплатіть переговори!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.PARENT,
    ),
    7 to BoardCard.Expenses(
        description = "Ти купив/ла нові сонцезахисні окуляри від Armani! Ну-у, ультрафіолет і все таке…",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    8 to BoardCard.Expenses(
        description = "Пора робити манікюр!",
        price = 30,
        priceTitle = "$30",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    9 to BoardCard.Expenses(
        description = "Нова акустична система з сабвуфером! Тепер про те, що ти їдеш, перехожі знатимуть за кілька хвилин до твого появлення!",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.AUTO_OWNER,
    ),
    10 to BoardCard.Expenses(
        description = "Донька вимагає такий самий набір косметики, як у мами! Інакше погрожує користуватися маміною косметикою…",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.PARENT,
    ),
    11 to BoardCard.Expenses(
        description = "Ти купив собі золоту затискачку для краватки! Побачив по телевізору, що це дуже солідно!",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.MEN,
    ),
    12 to BoardCard.Expenses(
        description = "У дитини неправильний прикус! Терміново потрібно ставити брекети, щоб не виріс «крокодилом»… Гарні зуби — це візитівка успішної людини!",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.PARENT,
    ),
    13 to BoardCard.Expenses(
        description = "Твоя дурна звичка «висмоктувати» бензин до останньої краплі принесла збитки. Заплати за новий бензонасос.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.AUTO_OWNER,
    ),
    14 to BoardCard.Expenses(
        description = "Влаштуй собі свято — виїхали з ліс і цілий день грали з друзями у гітару та волейбол! Задоволення не з дешевих, зате яке азартне!",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.ALL,
    ),
    15 to BoardCard.Expenses(
        description = "Ти купив/ла нові туфлі, а до них потрібна нова сумочка!",
        price = 100,
        priceTitle = "$50 + $50 = $100",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    16 to BoardCard.Expenses(
        description = "Дружина вимагає нове ліжко. Інакше відмовляється виконувати свої подружні обов’язки! А до шлюбу виконувала їх навіть у застібнутому ліфті!",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.MARRIED_M,
    ),
    17 to BoardCard.Expenses(
        description = "Ти купив/ла нову сукню, а до неї потрібні нові туфлі!",
        price = 150,
        priceTitle = "$100 + $50 = $150",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    18 to BoardCard.Expenses(
        description = "Твоя донька виходить заміж! Нарешті… Треба допомогти з весіллям, бо під вікнами вже палять феєрверки й горить бажання женитися…",
        price = 1000,
        priceTitle = "$1000",
        payer = PayerType.PARENT,
    ),
    19 to BoardCard.Expenses(
        description = "Терміново потрібна ручка Parker, щоб додати особистій солідності!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    20 to BoardCard.Expenses(
        description = "Речі розкидано по всій квартирі! Може, справа у неохайності? А може, настав час купити містку шафу-купе?",
        price = 1000,
        priceTitle = "$1000",
        payer = PayerType.APARTMENT_OWNER,
    ),
    21 to BoardCard.Expenses(
        description = "Купи сину новий шкіряний м’яч і встав нове скло на першому поверсі школи.",
        price = 150,
        priceTitle = "$50 + $100 = $150",
        payer = PayerType.PARENT,
    ),
    22 to BoardCard.Expenses(
        description = "Тебе затопили сусіди! Крім аналізів сечі з них узяти більше нічого. Тож розщедрись на ремонт!",
        price = 1500,
        priceTitle = "$1500",
        payer = PayerType.APARTMENT_OWNER,
    ),
    23 to BoardCard.Expenses(
        description = "Купив/ла нові гардини на вікна, щоб мешканці навпроти менше знали про твоє сексуальне життя.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    24 to BoardCard.Expenses(
        description = "Твій син вступив на платне відділення в інститут економіки — заплати за 1-й семестр.",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.PARENT,
    ),
    25 to BoardCard.Expenses(
        description = "Дитина знову порвала на футболі чергові кросівки. Радій, що займається спортом, а не підвалами з сигаретами шастає!",
        price = 60,
        priceTitle = "$60",
        payer = PayerType.PARENT,
    ),
    26 to BoardCard.Expenses(
        description = "Ти розорився/лася на домашньому кінотеатрі! Саме розорився/лася, бо домашній кінотеатр — покупка не з дешевих!",
        price = 2000,
        priceTitle = "$2000",
        payer = PayerType.ALL,
    ),
    27 to BoardCard.Expenses(
        description = "За любов до домашніх тварин треба платити! Іноді дуже дорого! Переклей по всій квартирі шпалери, пошкоджені кішкою.",
        price = 1500,
        priceTitle = "$1500",
        payer = PayerType.APARTMENT_OWNER,
    ),
    28 to BoardCard.Expenses(
        description = "У тебе закінчилася туш для вій! Купи нову!",
        price = 30,
        priceTitle = "$30",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    29 to BoardCard.Expenses(
        description = "У тебе нова подружка! Як же ще почати знайомство, якщо не з відвідування ресторану?!",
        price = 80,
        priceTitle = "$80",
        payer = PayerType.MEN,
    ),
    30 to BoardCard.Expenses(
        description = "Сів/сіла у своєму шикарному костюмі на тільки-но пофарбовану лавку… Заплати за хімчистку!",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.ALL,
    ),
    31 to BoardCard.Expenses(
        description = "Дитині терміново потрібне ліжечко! Будь ласка, оплатіть…",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.PARENT,
    ),
    32 to BoardCard.Expenses(
        description = "З вірою в те, що це додасть вам здоров’я, ти накупив/ла біодобавок! Твоя віра творить чудеса! Переважно фінансові — для виробників.",
        price = 80,
        priceTitle = "$80",
        payer = PayerType.ALL,
    ),
    33 to BoardCard.Expenses(
        description = "Випадково опинився/лася на шляху кортежу президента. За це у тебе забрали права і авто на штрафмайданчик. А кажуть, що влада належить народу!",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.AUTO_OWNER,
    ),
    34 to BoardCard.Expenses(
        description = "Усю ніч програв/ла з друзями у більярд! Тільки до ранку кулі почали хоча б інколи випадково падати в лузи…",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.MEN,
    ),
    35 to BoardCard.Expenses(
        description = "Твоя квартира на першому поверсі, а під твоїми вікнами постійно щось святкують якісь алкоголіки. Тож настав час поставити решітки на вікна!",
        price = 1000,
        priceTitle = "$1000",
        payer = PayerType.APARTMENT_OWNER,
    ),
    36 to BoardCard.Expenses(
        description = "Пора фарбувати волосся!",
        price = 40,
        priceTitle = "$40",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    37 to BoardCard.Expenses(
        description = "Дитина канючить велосипед, бо «у всіх уже є», а в нього ще немає — і через це «з ним не дружать»!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.PARENT,
    ),
    38 to BoardCard.Expenses(
        description = "У квартиру потрібен новий диван або м’який куточок для вітальні.",
        price = 800,
        priceTitle = "$800",
        payer = PayerType.APARTMENT_OWNER,
    ),
    39 to BoardCard.Expenses(
        description = "Пройшов/ла курс лікування від куріння. Одразу після завершення купив/ла блок сигарет. Заплати за лікування і за сигарети!",
        price = 130,
        priceTitle = "$100 + $30 = $130",
        payer = PayerType.ALL,
    ),
    40 to BoardCard.Expenses(
        description = "Залишив/ла автомобіль на ніч біля під’їзду. Тепер доведеться вставляти скло і купувати нову автомагнітолу та навігатор.",
        price = 700,
        priceTitle = "$200 + $200 + $300 = $700",
        payer = PayerType.AUTO_OWNER,
    ),
    41 to BoardCard.Expenses(
        description = "Твій син вимагає підсилювач і 2 колонки по 50 ват, щоб уся вулиця знала, яку саме музику він любить, і слухала її разом із ним!",
        price = 180,
        priceTitle = "$180",
        payer = PayerType.PARENT,
    ),
    42 to BoardCard.Expenses(
        description = "Ти купив/ла додому багатофункціональний тренажер! Сподіваєшся, що хоч це нарешті змусить тебе займатися спортом!",
        price = 1000,
        priceTitle = "$1000",
        payer = PayerType.ALL,
    ),
    43 to BoardCard.Expenses(
        description = "Залишив/ла на ніч увімкнені фари. Посадив/ла акумулятор.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.AUTO_OWNER,
    ),
    44 to BoardCard.Expenses(
        description = "У розпал зими через якусь аварію відключили опалення — терміново купи обігрівач!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    45 to BoardCard.Expenses(
        description = "Ваші кухонні ручки псуються від жорсткої води! Потрібна посудомийна машина!",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    46 to BoardCard.Expenses(
        description = "Ти купив/ла нову сумочку, а до неї — нову сукню і нові туфлі!",
        price = 200,
        priceTitle = "$50 + $100 + $50 = $200",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    47 to BoardCard.Expenses(
        description = "Ура! У тебе День народження! Ти запросив/ла найкращих друзів, накрив/ла шикарний стіл і подарував/ла кожному з них по 8 різних листівках!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    48 to BoardCard.Expenses(
        description = "Ваша квартира розташована на першому поверсі, а під вашими вікнами постійно щось святкують якісь алкоголіки. Тож настав час поставити решітки на вікна!",
        price = 1000,
        priceTitle = "$1000",
        payer = PayerType.APARTMENT_OWNER,
    ),
    49 to BoardCard.Expenses(
        description = "У дитини терміново потрібне ліжечко! Будьте ласкаві, оплатіть…",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.PARENT,
    ),
    50 to BoardCard.Expenses(
        description = "Ви втомилися купувати нові автомобільні дзеркала і поставили в машину дуже гучну сигналізацію з зворотним зв’язком!",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.AUTO_OWNER,
    ),
    51 to BoardCard.Expenses(
        description = "У тебе закінчився набір тіней!",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    52 to BoardCard.Expenses(
        description = "Не втрималася й купила собі золоті сережки!",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    53 to BoardCard.Expenses(
        description = "Відвідав футбольний матч «Динамо-Київ» — «Шахтар». Там така напруга, що довелося заплатити і за квиток, і за пиво!",
        price = 160,
        priceTitle = "$100 + $60 = $160",
        payer = PayerType.MEN,
    ),
    54 to BoardCard.Expenses(
        description = "Купила собі абонемент у солярій!",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    55 to BoardCard.Expenses(
        description = "Порушив правила паркування, і твою машину забрав евакуатор. Заплати за штрафмайданчик і послуги евакуатора.",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.AUTO_OWNER,
    ),
    56 to BoardCard.Expenses(
        description = "Повертаючись із Криму до Києва, намотав зайві 100 км біля Миколаєва. Щоб це не повторювалося — купи в машину навігатор!",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.AUTO_OWNER,
    ),
    57 to BoardCard.Expenses(
        description = "Купив собі новий крутий мобільний телефон із сенсорним екраном. Дзвонити з нього незручно, але ж який модний!",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.ALL,
    ),
    58 to BoardCard.Expenses(
        description = "Відвідала SPA-салон! У програмі — маска зі скрабом, обгортання, кавітація, антицелюлітний масаж із морськими перлинами!",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    59 to BoardCard.Expenses(
        description = "Ти все ще користуєшся телевізором зі старою трубкою? У всіх уже плазмові панелі! Настав час долучитися до технічного прогресу!",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.ALL,
    ),
    60 to BoardCard.Expenses(
        description = "Досить боятися вантажівок ночами! Купи собі ксенонові фари!",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.AUTO_OWNER,
    ),
    61 to BoardCard.Expenses(
        description = "У тебе зламалася пральна машина! Майстер сказав, що ремонт дорожчий за нову. Купи нову пральну машину.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.ALL,
    ),
    62 to BoardCard.Expenses(
        description = "Твоє авто знову не заводиться — акумулятору кінець. Купи новий!",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.AUTO_OWNER,
    ),
    63 to BoardCard.Expenses(
        description = "Купила новий фен і плойку, бо старі вже не тягнуть твої експерименти з волоссям.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    64 to BoardCard.Expenses(
        description = "Твій син на день народження замовив скейтборд. «Мама, усі вже катаються!»",
        price = 80,
        priceTitle = "$80",
        payer = PayerType.PARENT,
    ),
    65 to BoardCard.Expenses(
        description = "Протік дах — знову ця осіння романтика з мискою під краплею!",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.APARTMENT_OR_HOUSE_OWNER,
    ),
    66 to BoardCard.Expenses(
        description = "У тебе згоріла мікрохвильовка — нова модель з грилем уже чекає на тебе в магазині!",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.ALL,
    ),
    67 to BoardCard.Expenses(
        description = "Сусідка продала свої речі на OLX і тепер має нову праску. Ти ж не гірша — купи собі сучасну парову праску з розпилювачем!",
        price = 80,
        priceTitle = "$80",
        payer = PayerType.ALL,
    ),
    68 to BoardCard.Expenses(
        description = "Ти так поспішала, що залишила каву на даху автомобіля. Кава — $3, але мийка салону — дорожча.",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.AUTO_OWNER,
    ),
    69 to BoardCard.Expenses(
        description = "Твоя подруга зробила манікюр із камінням Swarovski. Тепер ти не можеш дивитися на свої нігті без сліз.",
        price = 60,
        priceTitle = "$60",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    70 to BoardCard.Expenses(
        description = "Твій чоловік розбив вазу з Китаю, яка стояла ще від бабусі. Купіть нову — хоча б для душевної рівноваги.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    71 to BoardCard.Expenses(
        description = "Улюблений кіт порвав нові гардини. Ти сердито подзвонила подрузі, а вона сказала: «Ну що ж, штори — це витратний матеріал». Купи нові!",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.APARTMENT_OR_HOUSE_OWNER,
    ),
    72 to BoardCard.Expenses(
        description = "Ти забула вимкнути праску, поки виходила за дитиною до школи. Добре, що нічого не згоріло — але майстерня вже виставила рахунок за ремонт розетки.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    73 to BoardCard.Expenses(
        description = "Твоя дитина намалювала фломастером на стіні «сімейний портрет». Не сварись — просто зроби косметичний ремонт.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.PARENT,
    ),
    74 to BoardCard.Expenses(
        description = "Купила крем із золотими частинками — і вже три дні чекаєш дива.",
        price = 120,
        priceTitle = "$120",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    75 to BoardCard.Expenses(
        description = "Твій чоловік випадково налив бензин замість дизеля — тепер двигуну кінець.",
        price = 600,
        priceTitle = "$600",
        payer = PayerType.AUTO_OWNER,
    ),
    76 to BoardCard.Expenses(
        description = "Купив новий пилосос із аквафільтром. Тепер пилу нема, але зникли і гроші.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.ALL,
    ),
    77 to BoardCard.Expenses(
        description = "Твоєму телефону кінець — ти впустила його у ванну, коли слухала музику.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.ALL,
    ),
    78 to BoardCard.Expenses(
        description = "Купила нові кросівки для занять у спортзалі — але туди так і не пішла.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    79 to BoardCard.Expenses(
        description = "Твій син вирішив стати барабанщиком. Купи йому барабанну установку — і терпіння!",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.PARENT,
    ),
    80 to BoardCard.Expenses(
        description = "Зламався холодильник, і тепер твій обід живе власним життям. Час купити новий!",
        price = 600,
        priceTitle = "$600",
        payer = PayerType.ALL,
    ),
    81 to BoardCard.Expenses(
        description = "Твій пес з’їв улюблені кросівки. Тепер тобі потрібна нова пара — і, можливо, новий пес.",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.ANIMAL_OWNER,
    ),
    82 to BoardCard.Expenses(
        description = "Ти нарешті вирішила зробити собі губи «трохи об’ємнішими». Лікар сказав: «Просто трохи» коштує дорожче.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    83 to BoardCard.Expenses(
        description = "У тебе зламалася кавоварка. День без кави — як рік без життя.",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.ALL,
    ),
    84 to BoardCard.Expenses(
        description = "Донька потрапила в «танцювальну лихоманку» — записала себе на сучасні танці, ще й на костюм треба!",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.PARENT,
    ),
    85 to BoardCard.Expenses(
        description = "Твоя машина втратила бампер, бо ти «злегка» торкнувся паркану сусіда.",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.AUTO_OWNER,
    ),
    86 to BoardCard.Expenses(
        description = "Купила абонемент у спортзал на рік уперед, бо «з понеділка почну нове життя».",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    87 to BoardCard.Expenses(
        description = "Твій чоловік випадково виправ сорочку разом із гаманцем. Новий гаманець і всі документи — не розкіш, а необхідність.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    88 to BoardCard.Expenses(
        description = "Купив нові зимові шини. І зрозумів, що тепер грошей не вистачає навіть на бензин.",
        price = 600,
        priceTitle = "$600",
        payer = PayerType.AUTO_OWNER,
    ),
    89 to BoardCard.Expenses(
        description = "Дитина залізла в інтернет і замовила 10 іграшок. Кур’єр уже в дверях.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.PARENT,
    ),
    90 to BoardCard.Expenses(
        description = "Твоя праска вибухнула, бо ти вирішила «попрасувати, доки ще гаряча». Купи нову і не ризикуй.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.ALL,
    ),
    91 to BoardCard.Expenses(
        description = "Ти переїла морозива й потрапила до лікаря. Діагноз: «щастя з ускладненнями».",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.ALL,
    ),
    92 to BoardCard.Expenses(
        description = "Твій ноутбук згорів після «легкого дощу» під час роботи на балконі.",
        price = 800,
        priceTitle = "$800",
        payer = PayerType.ALL,
    ),
    93 to BoardCard.Expenses(
        description = "Твою дитину вигнали з гуртка за бійку. Тепер треба купити миротворчі подарунки всім дітям у групі.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.PARENT,
    ),
    94 to BoardCard.Expenses(
        description = "Купила нову сукню для корпоративу — і зрозуміла, що без нових туфель не підеш.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    95 to BoardCard.Expenses(
        description = "Твоя машина застрягла в болоті. Виклик евакуатора + миття кузова.",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.AUTO_OWNER,
    ),
    96 to BoardCard.Expenses(
        description = "Твій телевізор показує лише «шум дощу». Майстер сказав: «Новий купити дешевше».",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.ALL,
    ),
    97 to BoardCard.Expenses(
        description = "Твоїй дитині потрібен новий смартфон, бо «в усіх у класі айфони».",
        price = 600,
        priceTitle = "$600",
        payer = PayerType.PARENT,
    ),
    98 to BoardCard.Expenses(
        description = "На роботі корпоратив у стилі «ретро». Купи костюм і аксесуари — бо інакше ти «зламаєш концепцію».",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.ALL,
    ),
    99 to BoardCard.Expenses(
        description = "Твоє авто знову постраждало від льодової бурульки. Цього разу — дах.",
        price = 700,
        priceTitle = "$700",
        payer = PayerType.AUTO_OWNER,
    ),
    100 to BoardCard.Expenses(
        description = "Купила швейну машинку, бо вирішила шити сама. Через тиждень передумала.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    101 to BoardCard.Expenses(
        description = "Купила дитині залізницю. Іноді ночами сама граєшся, думаючи, що в дитинстві в тебе такого не було.",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.PARENT,
    ),
    102 to BoardCard.Expenses(
        description = "Програла в лотерею. Хотіла легких грошей? Лотерея — це просто податок на людей, які не дружать із математикою.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.MEN,
    ),
    103 to BoardCard.Expenses(
        description = "Повертаючись із друзями після пива, ти сіла за кермо. Тепер доведеться заплатити штраф ДАІ, щоб не позбавили прав.",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.AUTO_OWNER,
    ),
    104 to BoardCard.Expenses(
        description = "У квартирі зробили ремонт, але труби не витримали — усе потекло! Виклич сантехніка й плати за нову роботу.",
        price = 3300,
        priceTitle = "$3 300",
        payer = PayerType.APARTMENT_OWNER,
    ),
    105 to BoardCard.Expenses(
        description = "Донька вимагає нові сукні для Барбі. Усі старі — «вийшли з моди». Звідки вона це знає?",
        price = 40,
        priceTitle = "$40",
        payer = PayerType.PARENT,
    ),
    106 to BoardCard.Expenses(
        description = "Купила абонемент у спортзал і вже на першому тренуванні заробила комплекс неповноцінності.",
        price = 60,
        priceTitle = "$60",
        payer = PayerType.ALL,
    ),
    107 to BoardCard.Expenses(
        description = "Упустила фотоапарат у воду. Сервіс відмовився ремонтувати — купуй новий.",
        price = 800,
        priceTitle = "$800",
        payer = PayerType.ALL,
    ),
    108 to BoardCard.Expenses(
        description = "Старший син розірвав шкільну форму, граючи у футбол. Купи нову.",
        price = 60,
        priceTitle = "$60",
        payer = PayerType.PARENT,
    ),
    109 to BoardCard.Expenses(
        description = "Син просить mp3-плеєр, щоб слухати рок. І не ділитися з мамою.",
        price = 80,
        priceTitle = "$80",
        payer = PayerType.PARENT,
    ),
    110 to BoardCard.Expenses(
        description = "Улюблений жакет постраждав від шампанського. Хімчистка чекає!",
        price = 150,
        priceTitle = "$150",
        payer = PayerType.APARTMENT_OWNER,
    ),
    111 to BoardCard.Expenses(
        description = "Син хоче купити гітару, щоб співати Цоя і підкорювати серця дівчат. Твоя частка — купівля гітари.",
        price = 100,
        priceTitle = "$100",
        payer = PayerType.PARENT,
    ),
    112 to BoardCard.Expenses(
        description = "Поїхала на картинг, щоб «відпочити від роботи». Але відпочинок вийшов дорогим!",
        price = 40,
        priceTitle = "$40",
        payer = PayerType.ALL,
    ),
    113 to BoardCard.Expenses(
        description = "Твій перший візит у суші-бар: спочатку боялася паличок, потім полюбила. Залишила чайові, забувши, що живеш не в Токіо.",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.FREE_W_OR_MARRIED_M,
    ),
    114 to BoardCard.Expenses(
        description = "Пішла з дитиною до зоопарку. Коли ж ти обіцяла минулого разу? І знову морозиво, поні й повітряні кульки.",
        price = 20,
        priceTitle = "$20",
        payer = PayerType.PARENT,
    ),
    115 to BoardCard.Expenses(
        description = "Син знову побився в школі — цього разу з вчителем фізкультури. Забирай із міліції.",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.PARENT,
    ),
    116 to BoardCard.Expenses(
        description = "Килим затишний, але не практичний. За два роки він вигорів і зіпсувався. Час купити новий.",
        price = 500,
        priceTitle = "$500",
        payer = PayerType.APARTMENT_OWNER,
    ),
    117 to BoardCard.Expenses(
        description = "Купила нову коляску — «щоб усі на майданчику заздрили».",
        price = 200,
        priceTitle = "$200",
        payer = PayerType.PARENT,
    ),
    118 to BoardCard.Expenses(
        description = "Пішла з дитиною до цирку. Квитки дорожчі, ніж у театр, але що не зробиш заради кульки та солодкої вати.",
        price = 50,
        priceTitle = "$50",
        payer = PayerType.PARENT,
    ),
    119 to BoardCard.Expenses(
        description = "Друзі покликали в покер — «на інтерес». Програла все, включно з упевненістю у власному розумі.",
        price = 250,
        priceTitle = "$250",
        payer = PayerType.MEN,
    ),
    120 to BoardCard.Expenses(
        description = "Чоловік вирішив, що стара пральна машина шумить, бо «втомилась». Купи нову.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.MARRIED_M,
    ),
    121 to BoardCard.Expenses(
        description = "Дитина розбила люстру. Не сварись — активність це теж ознака здоров’я. Купи нову.",
        price = 60,
        priceTitle = "$60",
        payer = PayerType.PARENT,
    ),
    122 to BoardCard.Expenses(
        description = "У квартирі зберігаєш гроші та цінності. Пора поставити броньовані двері.",
        price = 400,
        priceTitle = "$400",
        payer = PayerType.APARTMENT_OWNER,
    ),
    123 to BoardCard.Expenses(
        description = "Пішла на концерт гурту “Арія” — і втратила телефон. Може, сама, а може, «подарувала».",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.ALL,
    ),
    124 to BoardCard.Expenses(
        description = "Почався снігопад — саме час купити зимову гуму, щоб не ковзати в прямому й переносному сенсі.",
        price = 300,
        priceTitle = "$300",
        payer = PayerType.AUTO_OWNER,
    ),
    125 to BoardCard.Expenses(
        description = "Донька виходить заміж. Не з розрахунку, а з любові! Оплати весілля повністю.",
        price = 5000,
        priceTitle = "$5 000",
        payer = PayerType.PARENT,
    ),
)