package ua.vald_zx.game.rat.race.card.screen.board.cards

import ua.vald_zx.game.rat.race.card.shared.BoardCard
import ua.vald_zx.game.rat.race.card.shared.ShopType

val shoppingCards = mapOf(
    1 to BoardCard.Shopping(
        description = "Пристрій, який зовні нагадує автомобіль — Chery Amulet",
        price = 9500,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних із виплатами рівними частинами — 72 платежі по \$270. Або готівкою.",
    ),
    2 to BoardCard.Shopping(
        description = "Непоказна квартира на Лісовому масиві з тарганами, щурами та люстрами під старовину. 2 кімнати, 45 м².",
        price = 120000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних із виплатами рівними частинами — 300 платежів по \$1 000. Або готівкою.",
    ),
    3 to BoardCard.Shopping(
        description = "Автомобіль (ну, це голосно сказано) — Daewoo Matiz.",
        price = 7500,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних із виплатами рівними частинами — 72 платежі по \$210. Або готівкою.",
    ),
    4 to BoardCard.Shopping(
        description = "Елітна квартира на Позняках, 3 кімнати, 90 м², за 5 хвилин від метро.",
        price = 300000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних із виплатами рівними частинами — 300 платежів по \$3 000. Або готівкою.",
    ),
    5 to BoardCard.Shopping(
        description = "Елітна квартира на Хрещатику із запахом МакДональдза під вікнами. 4 кімнати, 100 м².",
        price = 600000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних із виплатами рівними частинами — 300 платежів по \$6 000. Або готівкою.",
    ),
    6 to BoardCard.Shopping(
        description = "Моторний катер \"Окунь\" — маленький і тісний човен, потрібен лише для того, щоб перейти на той бік річки.",
        price = 300000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    7 to BoardCard.Shopping(
        description = "Шикарний особняк на Осокорках з видом на річку та парканом із колючого дроту. 3 кімнати, 190 м².",
        price = 400000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    8 to BoardCard.Shopping(
        description = "Шикарний двоповерховий котедж у передмісті, у престижному районі, де сусіди дивляться зверху вниз. 4 кімнати, 240 м².",
        price = 400000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    9 to BoardCard.Shopping(
        description = "Розкішний і швидкий моторний катер із двома спальнями — \"Bavaria 38\". Водотоннажність — 8 тонн.",
        price = 900000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    10 to BoardCard.Shopping(
        description = "Спортивний автомобіль Audi TT — для тих, хто не боїться швидкості, податків і уваги ДАІ.",
        price = 100000,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних із виплатами рівними частинами — 72 платежі по \$1 605. Або готівкою.",
    ),
    11 to BoardCard.Shopping(
        description = "Звичайну квартиру в Академмістечку з видом на озеро, шашличників і комарів. 2 кімнати, 54 м².",
        price = 150000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних, 300 платежів по \$1 500. Або готівкою.",
    ),
    12 to BoardCard.Shopping(
        description = "Автомобіль, схожий на автомобіль — Volkswagen Passat.",
        price = 28000,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних, 72 платежі по \$770. Або готівкою.",
    ),
    13 to BoardCard.Shopping(
        description = "Представницький автомобіль Lexus RX 470 — солідний вигляд, ще солідніший податок на розкіш.",
        price = 180000,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних, 72 платежі по \$4 070. Або готівкою.",
    ),
    14 to BoardCard.Shopping(
        description = "Швидкохідну прогулянкову яхту \"Princess V45\", водотоннажність 12 тонн, потужність 700 к.с.",
        price = 800000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    15 to BoardCard.Shopping(
        description = "Будинок біля Київської кільцевої дороги, із запахом вихлопних газів і видом на супермаркет METRO. 2 поверхи, 240 м².",
        price = 500000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    16 to BoardCard.Shopping(
        description = "Стара квартира на Вітряних горах, у Києві, де відчуття, ніби ти в Чорнобилі. 1 кімната, 30 м².",
        price = 100000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних, 300 платежів по \$1 000. Або готівкою.",
    ),
    17 to BoardCard.Shopping(
        description = "Спортивний автомобіль Ferrari FF — якщо ти любиш швидкість, гучність і ризик залишитися без водійських прав.",
        price = 350000,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних, 72 платежі по \$7 025. Або готівкою.",
    ),
    18 to BoardCard.Shopping(
        description = "Mercedes CLK-600 — автомобіль, непомітний для ДАІ (але не для податкової).",
        price = 300000,
        shopType = ShopType.AUTO,
        credit = "Можна взяти у кредит на 6 років під 17% річних, 72 платежі по \$6 335. Або готівкою.",
    ),
    19 to BoardCard.Shopping(
        description = "Приватний літак Gulfstream 450 бізнес-класу. Максимальна швидкість — 860 км/год, дальність польоту — 8000 км.",
        price = 27000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    20 to BoardCard.Shopping(
        description = "Убогий готель на Комсомольському масиві, без кухні, але з гордістю за свою сидячу ванну. 1 кімната, 22 м².",
        price = 70000,
        shopType = ShopType.APARTMENT,
        credit = "Можна взяти у кредит на 25 років під 17% річних, 300 платежів по \$1 500. Або готівкою.",
    ),
    21 to BoardCard.Shopping(
        description = "Квартиру в ПГТ Коцюбинське з ілюзією, що це вже майже Київ. 4 кімнати, 120 м².",
        price = 200000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$2 000.",
    ),
    22 to BoardCard.Shopping(
        description = "Гігантську океанську яхту \"Оріон\", створену для життя, розваг і розведення плісняви. Водотоннажність 15 000 т, потужність 10 000 к.с.",
        price = 17000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    23 to BoardCard.Shopping(
        description = "Квартиру на Троєщині в недобудові з вічними обіцянками «здачі через пів року». 4 кімнати, 100 м².",
        price = 200000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$4 000.",
    ),
    24 to BoardCard.Shopping(
        description = "Представницький автомобіль Porsche Cayenne — для тих, хто любить великі чекі на СТО й дизель по ціні авіаційного палива.",
        price = 150000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$4 105.",
    ),
    25 to BoardCard.Shopping(
        description = "Приватний літак Falcon 7X, макс. швидкість — 950 км/год, дальність польоту — 6000 км.",
        price = 22000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    26 to BoardCard.Shopping(
        description = "Автомобіль як автомобіль — Skoda Octavia.",
        price = 26000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$705.",
    ),
    27 to BoardCard.Shopping(
        description = "Моторну яхту \"Princess 95\" з навігаційною системою та каютою для его. Водотоннажність 90 т, потужність 3000 к.с.",
        price = 9000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    28 to BoardCard.Shopping(
        description = "Зам suburban-будинок з банею та басейном, де дощ і бруд перемагають навіть позашляховик. 2 поверхи, 120 м².",
        price = 70000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    29 to BoardCard.Shopping(
        description = "Квартиру на Троєщині з панорамним видом на будмайданчик і сусідський гараж. 3 кімнати, 100 м².",
        price = 300000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$3 000.",
    ),
    30 to BoardCard.Shopping(
        description = "Приватний літак Falcon 900 (бізнес-клас). Макс. швидкість — 950 км/год, дальність польоту — 7600 км.",
        price = 23000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    31 to BoardCard.Shopping(
        description = "Особняк у Кончі-Заспі з власним пляжем на Дніпрі і сусідами депутатами та олігархами. 3 поверхи, 400 м².",
        price = 4000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    32 to BoardCard.Shopping(
        description = "Елітну квартиру в новобудові на Троєщині, де ще будують той самий під'їзд. 3 кімнати, 110 м².",
        price = 300000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$3 000.",
    ),
    33 to BoardCard.Shopping(
        description = "Парусну яхту \"Ураган\" з резервним дизельним двигуном. Водотоннажність 30 т, потужність 1000 к.с.",
        price = 1200000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    34 to BoardCard.Shopping(
        description = "Шикарний особняк у центрі Києва навпроти Лаври, який коштує, як половина ПТГ Луганської області. 3 поверхи, 640 м².",
        price = 8000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    35 to BoardCard.Shopping(
        description = "Родове помістя під Києвом із лісом і річкою, де можна ховатися від податків і родичів. 2 поверхи, 150 м².",
        price = 350000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    36 to BoardCard.Shopping(
        description = "Елітну квартиру біля Верховної Ради з вікнами на Маріїнський парк. 3 кімнати, 210 м².",
        price = 1000000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$10 000.",
    ),
    37 to BoardCard.Shopping(
        description = "Приватний літак Challenger 850 (бізнес-клас). Макс. швидкість — 800 км/год, дальність — 8000 км.",
        price = 22000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    38 to BoardCard.Shopping(
        description = "Скромну яхту \"Акула\", яка насправді підходить тільки для рибалки на Дніпрі. Водотоннажність 4 т, потужність 300 к.с.",
        price = 250000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    39 to BoardCard.Shopping(
        description = "Квартиру в ПГТ Вишневе, з виглядом на рейки та траси до Києва. 3 кімнати, 70 м².",
        price = 200000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$2 000.",
    ),
    40 to BoardCard.Shopping(
        description = "Елітну квартиру в житловому масиві «Час року», 6 кімнат, 140 м².",
        price = 450000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$4 500.",
    ),
    41 to BoardCard.Shopping(
        description = "Елітну квартиру на Осокорках, за 5 хвилин від метро. 3 кімнати, 80 м².",
        price = 250000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$2 500.",
    ),
    42 to BoardCard.Shopping(
        description = "Представницький автомобіль Toyota Land Cruiser — символ надійності й любові до витрат на пальне.",
        price = 150000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$4 105.",
    ),
    43 to BoardCard.Shopping(
        description = "Достойний автомобіль Toyota Camry — не спорткар, але начальник подумає.",
        price = 40000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$1 095.",
    ),
    44 to BoardCard.Shopping(
        description = "Достойний автомобіль Ford Mondeo, у якому все скрипить, але ти все ще стильна.",
        price = 40000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$1 095.",
    ),
    45 to BoardCard.Shopping(
        description = "Приватний літак Gulfstream 550 бізнес-класу. Макс. швидкість — 870 км/год, дальність — 8500 км.",
        price = 24000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    46 to BoardCard.Shopping(
        description = "Квартиру в центрі Києва з вікнами на Софійський собор. 4 кімнати, 96 м².",
        price = 600000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$6 000.",
    ),
    47 to BoardCard.Shopping(
        description = "Opel Vectra — автомобіль, що точно «як автомобіль».",
        price = 24000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$660.",
    ),
    48 to BoardCard.Shopping(
        description = "Моторну яхту \"Princess 54\" для подорожей із комфортом. Водотоннажність — 16 т, потужність — 1400 к.с.",
        price = 1400000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    49 to BoardCard.Shopping(
        description = "Моторну яхту \"Princess 75\" для життя в морі або втечі від новин. Водотоннажність — 25 т, потужність — 1900 к.с.",
        price = 1900000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    50 to BoardCard.Shopping(
        description = "Land Rover Range Rover — представницький автомобіль, що любить пальне більше, ніж людей.",
        price = 100000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$2 770.",
    ),
    51 to BoardCard.Shopping(
        description = "Будинок у Києві на Кіровоградській, із видом на СТО, що стоїть у пробках. 2 поверхи, 280 м².",
        price = 600000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    52 to BoardCard.Shopping(
        description = "Особняк на Південному березі Криму з пулеметом на даху (для безпеки) і тарганами в підвалі. 3 поверхи, 450 м².",
        price = 5000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    53 to BoardCard.Shopping(
        description = "Елітну квартиру в новобудові на Троєщині, з видом на ліс і поле до горизонту. 3 кімнати, 105 м².",
        price = 250000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$2 500.",
    ),
    54 to BoardCard.Shopping(
        description = "Шикарний особняк біля Ботанічного саду, з басейном і чутками, що тут живе Бред Пітт. 4 поверхи, 600 м².",
        price = 6000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    55 to BoardCard.Shopping(
        description = "Квартира в новобудові на Осокорках, 3 кімнати, 80 м², для тих, хто вірить у чудеса з документами.",
        price = 250000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$2 500.",
    ),
    56 to BoardCard.Shopping(
        description = "Шикарний особняк на лівому березі Дніпра, із видом на Лавру й японський сад у дворі. 3 поверхи, 500 м².",
        price = 5000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    57 to BoardCard.Shopping(
        description = "Приватний літак Gulfstream 550 — бо ти вже пройшла етап бізнес-класу. Макс. швидкість — 870 км/год, дальність — 8500 км.",
        price = 24000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    58 to BoardCard.Shopping(
        description = "Елітну квартиру біля моря, 5 кімнат, 140 м², де чайки кричать замість сусідів.",
        price = 450000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$4 500.",
    ),
    59 to BoardCard.Shopping(
        description = "Шикарну яхту \"Піратор\", водотоннажність — 220 т, потужність — 5000 к.с.",
        price = 5000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    60 to BoardCard.Shopping(
        description = "Land Rover Range Rover (так, ще один) — бо одного завжди мало.",
        price = 100000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$2 770.",
    ),
    61 to BoardCard.Shopping(
        description = "Особняк у Солом'янському парку з мансардою, зимовим садом і видом на сусідів, які знімаються в токшоу. 3 поверхи, 180 м².",
        price = 400000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки за готівку.",
    ),
    62 to BoardCard.Shopping(
        description = "Парусно-дизельну яхту \"Esmeralda 21\", водотоннажність — 200 т, потужність — 6000 к.с.",
        price = 8000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    63 to BoardCard.Shopping(
        description = "Елітну квартиру в центрі Києва на вул. Прорізній, з видом на Хрещатик. 4 кімнати, 120 м².",
        price = 800000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$8 000.",
    ),
    64 to BoardCard.Shopping(
        description = "Особняк на Печерську, 2 поверхи, 480 м², із видом на Дніпро і на себе в дзеркалі успіху.",
        price = 1000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    65 to BoardCard.Shopping(
        description = "Приватний літак Cessna Citation X — 950 км/год, 6000 км дальність польоту.",
        price = 10000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    66 to BoardCard.Shopping(
        description = "Елітну квартиру на Оболоні з видом на Дніпро. 4 кімнати, 140 м².",
        price = 400000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$4 000.",
    ),
    67 to BoardCard.Shopping(
        description = "Mazda 6 — достойний автомобіль для тих, хто ще вірить у японську якість.",
        price = 36000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$1 005.",
    ),
    68 to BoardCard.Shopping(
        description = "Моторну яхту \"Сиренада\" — 8 місць, 150 т, 6000 к.с., ідеальна для гучних вечірок і тихих розлучень.",
        price = 8000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    69 to BoardCard.Shopping(
        description = "Chevrolet Lacetti — автомобіль, який виглядає як покупка, а не як мрія.",
        price = 16000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$445.",
    ),
    70 to BoardCard.Shopping(
        description = "BMW 750 — представницький автомобіль для тих, хто ще не встиг купити Cayenne.",
        price = 180000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$5 005.",
    ),
    71 to BoardCard.Shopping(
        description = "Парусну яхту \"Brigantine\" із вертолітним майданчиком, 170 т, 8000 к.с.",
        price = 12000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    72 to BoardCard.Shopping(
        description = "Квартиру на Печерську з місцем у підземному паркінгу. 5 кімнат, 130 м².",
        price = 650000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$6 500.",
    ),
    73 to BoardCard.Shopping(
        description = "Квартиру на Русанівці, з виглядом на задухи та човни-безмоторки. 2 кімнати, 45 м².",
        price = 150000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$1 500.",
    ),
    74 to BoardCard.Shopping(
        description = "Приватний літак Embraer Legacy 650, макс. швидкість — 900 км/год, дальність — 7000 км.",
        price = 30000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    75 to BoardCard.Shopping(
        description = "Mitsubishi Lancer X — класика для тих, хто любить шум глушника більше, ніж тишу.",
        price = 24000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$605.",
    ),
    76 to BoardCard.Shopping(
        description = "Квартиру на Липській з видом на офіс партії регіонів. 5 кімнат, 150 м².",
        price = 750000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17% річних, 300 платежів по \$7 500.",
    ),
    77 to BoardCard.Shopping(
        description = "BMW 540 — достойний автомобіль, який ще пам'ятає, що таке задній привід.",
        price = 90000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17% річних, 72 платежі по \$2 505.",
    ),
    78 to BoardCard.Shopping(
        description = "Літак Hawker Horizon, макс. швидкість — 870 км/год, дальність — 8000 км.",
        price = 8000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    79 to BoardCard.Shopping(
        description = "Літак Global Express, 900 км/год, 9500 км дальність — для тих, хто літає від проблем.",
        price = 50000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    80 to BoardCard.Shopping(
        description = "Літак Як-40, 1975 року випуску — трошки трясе, але романтично. 850 км/год, дальність — 1300 км.",
        price = 1000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    81 to BoardCard.Shopping(
        description = "Розкішну моторну яхту \"Мрія\" із басейном на верхній палубі, водотоннажність — 120 т, потужність — 4000 к.с.",
        price = 9000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    82 to BoardCard.Shopping(
        description = "Квартиру на проспекті Волкова з видом на дрімучий ліс, де завжди тихо і трохи моторошно. 3 кімнати, 74 м².",
        price = 200000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17 %, 300 платежів по \$2 000.",
    ),
    83 to BoardCard.Shopping(
        description = "Приватний літак Hawker Horizon 900 XP, 900 км/год, 5000 км дальність польоту — щоб втекти від застряглого митця в сусідах.",
        price = 10000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    84 to BoardCard.Shopping(
        description = "Особняк у Пущі-Водиці з власним виходом до Дніпра, альтанкою і сусідами олігархами. 3 поверхи, 260 м².",
        price = 2800000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    85 to BoardCard.Shopping(
        description = "BMW X5 — представницький автомобіль для тих, хто любить великі чекі на СТО.",
        price = 150000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$4 105.",
    ),
    86 to BoardCard.Shopping(
        description = "Моторну яхту \"Princess 105\" для великих компаній, водотоннажність 29 т, потужність 2000 к.с.",
        price = 2200000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    87 to BoardCard.Shopping(
        description = "Автомобіль ЗАЗ \"Славута\" — час ганьби і слави водночас. Твоя праця оцінена в метал.",
        price = 6000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$165.",
    ),
    88 to BoardCard.Shopping(
        description = "Літак Gulfstream 200, макс. швидкість 800 км/год, дальність 5000 км — мінімум клас бізнес.",
        price = 7000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    89 to BoardCard.Shopping(
        description = "Nissan Murano — представницький автомобіль, який світиться словом \"комфорт\".",
        price = 75000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$2 055.",
    ),
    90 to BoardCard.Shopping(
        description = "Елітну квартиру на Липках із зимовим садом і тренажерним залом на даху. 12 кімнат, 260 м².",
        price = 900000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17 %, 300 платежів по \$9 000.",
    ),
    91 to BoardCard.Shopping(
        description = "Яхту \"Princess V70\" — 35 т, 3000 к.с., для прогулянок вздовж берегів власного успіху.",
        price = 1000000,
        shopType = ShopType.YACHT,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    92 to BoardCard.Shopping(
        description = "Приватний літак Bombardier Challenger 300, 800 км/год, 6000 км дальність — для ділових та емоційних польотів.",
        price = 20000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    93 to BoardCard.Shopping(
        description = "Daewoo Lanos — вибір таксиста й людини, яка ще вірить у долю.",
        price = 10000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$280.",
    ),
    94 to BoardCard.Shopping(
        description = "Gulfstream G650 — приватний літак зі швидкістю 950 км/год і дальністю 13 000 км.",
        price = 18000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    95 to BoardCard.Shopping(
        description = "Lamborghini Diablo — автомобіль, який змушує сусідів перестати вітатися.",
        price = 300000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$8 305.",
    ),
    96 to BoardCard.Shopping(
        description = "Honda Accord — достойний автомобіль для тих, хто любить баланс між швидкістю й спокоєм.",
        price = 40000,
        shopType = ShopType.AUTO,
        credit = "Кредит на 6 років під 17 %, 72 платежі по \$1 105.",
    ),
    97 to BoardCard.Shopping(
        description = "Літак Gulfstream 150, макс. швидкість 800 км/год, дальність 8000 км.",
        price = 8000000,
        shopType = ShopType.FLY,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    98 to BoardCard.Shopping(
        description = "Особняк на правому березі Дніпра, з видом на Лавру, терасою й власною сауною. 4 поверхи, 550 м².",
        price = 7000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
    99 to BoardCard.Shopping(
        description = "Квартиру на Десятинній вулиці, 4 кімнати, 100 м², з виглядом на Софію Київську.",
        price = 1000000,
        shopType = ShopType.APARTMENT,
        credit = "Кредит на 25 років під 17 %, 300 платежів по \$10 000.",
    ),
    100 to BoardCard.Shopping(
        description = "Особняк у Карпатах, з видом на водоспад, каміном і басейном на схилі. 4 поверхи, 360 м².",
        price = 3000000,
        shopType = ShopType.HOUSE,
        credit = "Не кредитується! Тільки готівкою.",
    ),
)